// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRlpKFM51yN_uAKgO5Ad9A0cizm_JfTHQ',
    appId: '1:744561684493:web:1a29f9df60f3f9ee316544',
    messagingSenderId: '744561684493',
    projectId: 'music-camp-45f37',
    authDomain: 'music-camp-45f37.firebaseapp.com',
    storageBucket: 'music-camp-45f37.appspot.com',
    measurementId: 'G-JN8G5QGXK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98ACtSKyCmv7W2Yb20bcUyQjKgLRQZqU',
    appId: '1:744561684493:android:257650fc940925ba316544',
    messagingSenderId: '744561684493',
    projectId: 'music-camp-45f37',
    storageBucket: 'music-camp-45f37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9nKyNoPM8WuOkWfIyAFE-YaUpnWTgsH0',
    appId: '1:744561684493:ios:9c94f4b960c5c8bd316544',
    messagingSenderId: '744561684493',
    projectId: 'music-camp-45f37',
    storageBucket: 'music-camp-45f37.appspot.com',
    iosBundleId: 'com.example.musicCamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9nKyNoPM8WuOkWfIyAFE-YaUpnWTgsH0',
    appId: '1:744561684493:ios:9c94f4b960c5c8bd316544',
    messagingSenderId: '744561684493',
    projectId: 'music-camp-45f37',
    storageBucket: 'music-camp-45f37.appspot.com',
    iosBundleId: 'com.example.musicCamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRlpKFM51yN_uAKgO5Ad9A0cizm_JfTHQ',
    appId: '1:744561684493:web:5d1f589361b6c6cd316544',
    messagingSenderId: '744561684493',
    projectId: 'music-camp-45f37',
    authDomain: 'music-camp-45f37.firebaseapp.com',
    storageBucket: 'music-camp-45f37.appspot.com',
    measurementId: 'G-YRSYVKLKDX',
  );
}
